plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/nexo_jo/Desktop/Nexo_workspace/Nexo_web_bro_1"
publishOrigin = "config"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]